export const site = {
  name: 'DAHO',
  fullName: 'Diego Hernández',
  alternateName: 'DAHO',
  siteUrl: 'https://www.dahoofficial.com',
  email: 'dahoreddiegohernandez+dahoofficial@gmail.com',
  jobTitle: 'Senior Front End Developer',
  description:
    'Senior Front End Developer with 10+ years of experience. Gamer, Content Creator & Coexister. Creator of myappcube.',
  keywords: [
    'Diego Hernandez',
    'Diego Hernández',
    'Daho',
    'DAHO',
    'dahored',
    'dahoofficial',
    'frontend developer',
    'Senior Front End Developer',
    'developer Colombia',
    'React developer',
    'Next.js developer',
    'TypeScript developer',
    'gaming',
    'content creator',
    'Daho Gaming',
    'Daho Adventures',
    'Daho Coexist',
    'myappcube',
    'El Infiltrado',
    'Oculto',
    'coexister',
  ],
  socials: {
    github: 'https://github.com/dahored',
    linkedin: 'https://www.linkedin.com/in/dahored/',
    youtube: 'https://www.youtube.com/@dahogaming',
    twitch: 'https://www.twitch.tv/dahored',
  },
  sameAs: [
    'https://github.com/dahored',
    'https://www.linkedin.com/in/dahored/',
    'https://www.youtube.com/@dahogaming',
    'https://www.twitch.tv/dahored',
    'https://www.instagram.com/daho.gaming/',
    'https://x.com/daho_gaming',
    'https://kick.com/dahored',
    'https://www.tiktok.com/@dahored',
    'https://www.facebook.com/dahored',
  ],
};
